const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');

test('payment and public RPCs preserve validation, atomic writes and access boundaries', async () => {
 const db = new PGlite();
 const call = async (sql, args=[]) => (await db.query(sql,args)).rows[0].result;
 try {
  await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
  for (const file of ['backend/models/database.postgres.sql','supabase/migrations/202609120001_api_access.sql','supabase/migrations/202609120003_payments_public.sql']) await db.exec(fs.readFileSync(path.join(__dirname,'../..',file),'utf8'));
  await db.exec(`insert into public.users(id,name,email,password,role) values(1,'Admin','admin@example.test','x','admin'),(2,'Officer','officer@example.test','x','apprehending_officer'),(3,'Other','other@example.test','x','apprehending_officer');
   insert into public.vehicles(id,plate_number,vehicle_type,owner_name,owner_email) values(1,'ABC-123','car','Current Owner','current@example.test');
   insert into public.tickets(id,ticket_number,user_id,vehicle_id,violation_id,date_issued,time_issued,owner_name_at_issue,owner_email_at_issue) select i,'TEST-'||i,2,1,1,current_date,'10:00','Snapshot Owner','snapshot@example.test' from generate_series(1,8) i;
   update public.tickets set owner_name_at_issue='',owner_email_at_issue='' where id=2;
   update public.tickets set date_issued=current_date-16 where id=3;
   update public.tickets set status='paid' where id=4;
   set role service_role;`);
  const dispute = await call('select public.tvtms_public_dispute($1,$2) result',['TEST-1','A valid dispute reason']);
  assert.ok(dispute.disputeId);
  const saved=(await db.query('select * from public.disputes where id=$1',[dispute.disputeId])).rows[0];
  assert.equal(saved.contact_email,'snapshot@example.test'); assert.equal(saved.submitted_by,null);
  assert.equal((await call('select public.tvtms_public_dispute($1,$2) result',['TEST-1','A valid dispute reason'])).statusCode,409);
  await call('select public.tvtms_public_dispute($1,$2) result',['TEST-2','A valid dispute reason']);
  assert.equal((await db.query('select contact_email from public.disputes where ticket_id=2')).rows[0].contact_email,'current@example.test');
  assert.equal((await call('select public.tvtms_public_dispute($1,$2) result',['TEST-3','A valid dispute reason'])).errorCode,'DISPUTE_DEADLINE_EXPIRED');
  assert.equal((await call('select public.tvtms_public_dispute($1,$2) result',['TEST-4','A valid dispute reason'])).statusCode,403);
  assert.equal((await call("select public.tvtms_dispute_create(5,'A valid dispute reason',3) result")).statusCode,403);
  const pay = (id,receipt,amount) => call("select public.tvtms_payment_record($1,$2,$3,current_date,'cash',null,1) result",[id,receipt,amount]);
  assert.equal((await pay(1,'OR-1',10)).errorCode,'ACTIVE_DISPUTE');
  assert.equal((await pay(5,'OR-OVER',501)).errorCode,'OVERPAYMENT');
  assert.equal((await pay(5,'OR-5',200)).paymentStatus,'partial');
  assert.equal((await pay(6,'OR-5',100)).errorCode,'OR_NUMBER_EXISTS');
  assert.equal((await pay(5,'OR-6',300)).nextStatus,'paid');
  assert.equal((await pay(5,'OR-7',1)).errorCode,'ALREADY_PAID');
  await pay(6,'OR-8',100);
  const internal=await call("select public.tvtms_dispute_create(6,'A valid dispute reason',2) result");
  assert.equal((await call("select public.tvtms_dispute_resolve($1,'approved','Valid resolution',1) result",[internal.disputeId])).errorCode,'PAYMENT_EXISTS');
  await call("select public.tvtms_dispute_resolve($1,'approved','Valid resolution',1) result",[dispute.disputeId]);
  assert.equal((await db.query('select status from public.tickets where id=1')).rows[0].status,'cancelled');
  assert.equal((await call("select public.tvtms_dispute_resolve($1,'rejected','Valid resolution',1) result",[dispute.disputeId])).errorCode,'DISPUTE_FINALIZED');
  const lookup=await call("select public.tvtms_public_lookup('ABC123',null) result");
  assert.equal(lookup.length,8); assert.equal(lookup.find(t=>t.id===5).remaining_balance,0); assert.equal('owner_email' in lookup[0],false);
  assert.equal((await call("select public.tvtms_public_summary('ABC123') result")).total_violations,7);
  assert.equal((await call('select public.tvtms_public_stats() result')).total_tickets,8);
  const vehicle=await call("select public.tvtms_public_vehicle('ABC123') result");
  assert.equal(vehicle.vehicles[0].plate_number,'ABC-123');
  assert.equal('sort_time' in vehicle.violations[0],false);
  assert.equal((await call("select public.tvtms_dispute_list(null,null,3) result")).length,0);
  assert.equal((await call("select public.tvtms_dispute_list(null,null,2) result")).length,3);
  await call("select public.tvtms_public_contact('Sender','sender@example.test','Subject','A valid message') result");
  assert.equal((await db.query('select count(*) from public.contact_messages')).rows[0].count,1);
  await db.exec("update public.users set status='inactive' where id=1");
  assert.equal((await call("select public.tvtms_public_contact('Sender','sender@example.test','Subject','A valid message') result")).statusCode,503);
  assert.equal((await db.query('select count(*) from public.contact_messages')).rows[0].count,1);
  await db.exec("update public.users set status='active' where id=1; reset role; create function public.reject_notification() returns trigger language plpgsql as $$begin raise exception 'notification unavailable'; end;$$; create trigger reject_notification before insert on public.notifications for each row execute function public.reject_notification(); set role service_role;");
  await assert.rejects(call("select public.tvtms_public_dispute('TEST-7','A valid dispute reason') result"),/notification unavailable/);
  assert.equal((await db.query('select count(*) from public.disputes where ticket_id=7')).rows[0].count,0);
  await assert.rejects(call("select public.tvtms_public_contact('Sender','sender@example.test','Subject','A valid message') result"),/notification unavailable/);
  assert.equal((await db.query('select count(*) from public.contact_messages')).rows[0].count,1);
  await db.exec("reset role; create function public.reject_history() returns trigger language plpgsql as $$begin raise exception 'history unavailable'; end;$$; create trigger reject_history before insert on public.ticket_status_history for each row execute function public.reject_history(); set role service_role;");
  await assert.rejects(pay(8,'OR-ROLLBACK',500),/history unavailable/);
  assert.equal((await db.query('select count(*) from public.payments where ticket_id=8')).rows[0].count,0);
  assert.equal((await db.query('select status from public.tickets where id=8')).rows[0].status,'unpaid');
  const pending=(await db.query('select id from public.disputes where ticket_id=2')).rows[0].id;
  await assert.rejects(call("select public.tvtms_dispute_resolve($1,'approved','Valid resolution',1) result",[pending]),/history unavailable/);
  assert.equal((await db.query('select status from public.disputes where id=$1',[pending])).rows[0].status,'submitted');
  assert.equal((await db.query('select status from public.tickets where id=2')).rows[0].status,'unpaid');
  await db.exec('reset role; set role anon;');
  await assert.rejects(call('select public.tvtms_public_stats() result'),/permission denied/);
 } finally { await db.close(); }
});
